# This is an auto generated file. If something isn't working
# correctly, see 'typegen.cr' in the project root


module Proton::Types
  # A file generated by the client.
  class InputFile::Generated < Types::InputFile
    include JSON::Serializable

    # String specifying the conversion applied to the original file; should be persistent across application restarts. Conversions beginning with '#' are reserved for internal TDLib usage
    property conversion : ::String

    # Expected size of the generated file; 0 if unknown
    property expected_size : ::Int32

    # Local path to a file from which the file is generated; may be empty if there is no such file
    property original_path : ::String? = nil

    def initialize(@conversion : ::String, @expected_size : ::Int32, @original_path : ::String? = nil)
    end
  end
end
