# This is an auto generated file. If something isn't working
# correctly, see 'typegen.cr' in the project root

require "./base"

module Proton::Types
  # Represents a local file.
  class LocalFile < Types::Base
    include JSON::Serializable

    # True, if it is possible to try to download or generate the file
    property can_be_downloaded : ::Bool

    # True, if the file can be deleted
    property can_be_deleted : ::Bool

    # True, if the file is currently being downloaded (or a local copy is being generated by some other means)
    property is_downloading_active : ::Bool

    # True, if the local copy is fully available
    property is_downloading_completed : ::Bool

    # Download will be started from this offset. downloaded_prefix_size is calculated from this offset
    property download_offset : ::Int32

    # If is_downloading_completed is false, then only some prefix of the file starting from download_offset is ready to be read. downloaded_prefix_size is the size of that prefix
    property downloaded_prefix_size : ::Int32

    # Total downloaded file bytes. Should be used only for calculating download progress. The actual file size may be bigger, and some parts of it may contain garbage
    property downloaded_size : ::Int32

    # Local path to the locally available file part; may be empty
    property path : ::String? = nil

    def initialize(@can_be_downloaded : ::Bool, @can_be_deleted : ::Bool, @is_downloading_active : ::Bool, @is_downloading_completed : ::Bool, @download_offset : ::Int32, @downloaded_prefix_size : ::Int32, @downloaded_size : ::Int32, @path : ::String? = nil)
    end
  end
end
